version: '3'

services:
  web:
    build: ./src
    ports: 
      - "8081:8080"
    networks:
      - backend
    environment:
      REDIS_URL: redis:6379
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - backend
    sysctls:
      net.core.somaxconn: 1024


networks:
  backend: